### ISSUE TITLE
Folder Architecture Setup

### ISSUE THREAD

**Issue by vini-cabral** [vini-cabral/rocketseat-challenge-rocketnews#1]
**Description:**
1. Create a simple folder structure with a main **folder** named **assets**, and two **subfolders** named **css** and **img**.
2. Set the font style in accordance with the _[figma design](https://www.figma.com/file/OVTHLjc2hi3MSQiYm9BplU/DD-%2F-RocketNews/duplicate)_.
3. Create a branch named development, and work from there.
4. Create the file index.html and insert the link to the style file. Print the message _"Hello, World"_ on the screen.

**Comment by vini-cabral-2** [comment]
All right, let's go!

**Comment by vini-cabral** [comment]
Great, job done!
