### ISSUE TITLE
Email Capture Form Development

### ISSUE THREAD

**Issue by vini-cabral** [vini-cabral/rocketseat-challenge-rocketnews#2]
**Description:**

1. In the figma project, there is no cell phone version.
2. Use the main tag, and within it define a container with self-adjusting width and self-centered along the x-axis. The container should have a maximum width of 720px.
3. In another moment the breakpoint for developing the desktop version will be defined.

**Comment by vini-cabral-2** [comment]
Initiated work!

**Comment by vini-cabral** [comment]
Very good, it was approved!
